name: Publish Node.js Package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      # Install
      - run: yarn install

      # Update version
      - name: Get version from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Update package version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions-bot@github.com"
          npm version ${{ env.RELEASE_VERSION }}

      # Push changes to the repo
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump version to ${{ env.RELEASE_VERSION }}

      # Publish package
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
